### ISSUE TITLE
Day 1

### ISSUE THREAD

**Issue by Erin-Codes** [Moipatit/Day-1#1]
Good job for familiarising yourself with just a few of the ways we could potentially make use of python in the realm of cybersecurity.
All three of your tasks have been completed. :) The affirmations API for task 2 was a pretty cool idea btw ;)

Optional
Attached are two additional resources for more information on how python is used in CS(both contain PDF):

-[ Link 1](https://ninja-ide.org/python-for-security-pentesters-pdf-download/)
- [Link 2](https://www.researchgate.net/publication/339196548_Cyber_Security_Tool_Kit_CyberSecTK_A_Python_Library_for_Machine_Learning_and_Cyber_Security)

**Comment by Moipatit** [comment]
Thank you for your feedback
